import os

base_dir = r"c:\Users\Athen\Desktop\m2web\locale"

en_dict = {
    "Accueil": "Home",
    "À Propos": "About",
    "Services & Solutions": "Services & Solutions",
    "Gros & B2B": "Wholesale & B2B",
    "Vente en Gros": "Wholesale",
    "Devenir Revendeur": "Become a Reseller",
    "Plateforme & Serveur GPS": "GPS Platform & Server",
    "Promotions": "Promotions",
    "Contact": "Contact",
    "Demander un Devis": "Request a Quote",
    "Lun-Ven": "Mon-Fri",
    "Sam": "Sat",
    "Dim": "Sun",
    "Garantie & Support Direct": "Warranty & Direct Support",
    "Fournisseur Agréé": "Certified Supplier",
    "TÉLÉMATIQUE MAROC": "TELEMATICS MOROCCO",
    "Prenez le Contrôle": "Take Control",
    "Total de Votre Flotte": "Of Your Fleet",
    "en Temps Réel": "in Real Time",
    "Traceurs 4G Certifiés": "Certified 4G Trackers",
    "Installation sur Site": "On-Site Installation",
    "Support 24/7 à Fès": "24/7 Support in Fez",
    "Nos Solutions GPS": "Our GPS Solutions",
    "Devis Express Gratuit": "Free Express Quote",
    "Trackers Installés": "Trackers Installed",
    "Flottes Gérées": "Fleets Managed",
    "Disponibilité Serveurs": "Server Uptime",
    "Pourquoi Choisir": "Why Choose",
    "Nos Solutions de": "Our Solutions for",
    "Télématique": "Telematics",
    "Découvrir la solution": "Discover the solution",
    "Traceurs GPS": "GPS Trackers",
    "& Équipements": "& Equipment",
    "Catalogue Complet": "Full Catalog",
    "En Stock": "In Stock",
    "Garanti 1 an": "1 Year Warranty",
    "Tarif indicatif": "Indicative price",
    "Sur devis": "On quote",
    "Commander": "Order",
    "ESPACE REVENDEURS & GROSSISTES": "RESELLER & WHOLESALE SPACE",
    "Ouvrir un Compte Pro": "Open a Pro Account",
    "Ce que disent nos": "What our",
    "Partenaires": "Partners",
    "Client Vérifié": "Verified Client",
    "Ils nous font confiance au Maroc": "They trust us in Morocco",
    "Rencontrez Notre Équipe": "Meet Our Team",
    "Adresse du Siège & Showroom": "Headquarters & Showroom Address",
    "Ligne Téléphonique Directe": "Direct Phone Line",
    "Email Commercial": "Sales Email",
    "Liens Rapides": "Quick Links",
    "Nos Solutions": "Our Solutions",
    "Contactez-nous": "Contact Us",
    "Tous droits réservés.": "All rights reserved.",
    "Actualités": "News",
    "Suivi GPS en temps réel": "Real-time GPS Tracking",
    "Gestion de flotte": "Fleet Management",
    "Contrôle de carburant": "Fuel Control",
    "Surveillance de température": "Temperature Monitoring",
    "Contactez-nous sur WhatsApp": "Contact us on WhatsApp",
    "Discutez avec nous": "Chat with us",
    "Toggle navigation": "Toggle navigation",
    "Offres & Promotions": "Deals & Promotions",
    "Exclusives": "Exclusive",
    "Voir toutes les offres": "See all deals",
    "Valable jusqu'au": "Valid until",
    "Votre message a été envoyé avec succès.": "Your message has been sent successfully.",
    "Votre demande a été envoyée avec succès.": "Your request has been sent successfully.",
    "Votre candidature a été envoyée avec succès.": "Your application has been sent successfully.",
    "Vérification anti-spam": "Anti-spam verification",
    "Réponse incorrecte. Veuillez réessayer.": "Incorrect answer. Please try again.",
    "Session de vérification expirée.": "Verification session expired.",
    "Demande Envoyée": "Request Sent",
    "Demande envoyée avec succès !": "Request sent successfully!",
    "Retour à l'accueil": "Back to home",
    "Téléphone": "Phone",
    "Envoyer la demande B2B": "Send B2B Request",
    "Envoyer ma demande": "Send my request",
    "Profiter de l'offre": "Take advantage of the offer",
    "Les Avantages du Programme Revendeur": "Reseller Program Benefits",
    "Marges Attractives": "Attractive Margins",
    "Stock Disponible": "Available Stock",
    "Support & Formation": "Support & Training",
    "Marque Blanche": "White Label",
    "Support Marketing": "Marketing Support",
    "Gestionnaire Dédié": "Dedicated Manager",
    "Niveaux de Partenariat": "Partnership Levels",
    "Découverte": "Discovery",
    "Le plus populaire": "Most Popular",
    "Pro": "Pro",
    "Distributeur": "Distributor",
    "Demande d'Ouverture de Compte Revendeur": "Reseller Account Opening Request"
}

ar_dict = {
    "Accueil": "الرئيسية",
    "À Propos": "من نحن",
    "Services & Solutions": "الخدمات والحلول",
    "Gros & B2B": "البيع بالجملة",
    "Vente en Gros": "البيع بالجملة",
    "Devenir Revendeur": "أصبح موزعاً",
    "Plateforme & Serveur GPS": "منصة وخادم GPS",
    "Promotions": "العروض",
    "Contact": "اتصل بنا",
    "Demander un Devis": "طلب عرض سعر",
    "Lun-Ven": "الإثنين-الجمعة",
    "Sam": "السبت",
    "Dim": "الأحد",
    "Garantie & Support Direct": "ضمان ودعم مباشر",
    "Fournisseur Agréé": "مورد معتمد",
    "TÉLÉMATIQUE MAROC": "تيليماتيك المغرب",
    "Prenez le Contrôle": "تحكّم بالكامل",
    "Total de Votre Flotte": "في أسطول مركباتك",
    "en Temps Réel": "في الوقت الحقيقي",
    "Traceurs 4G Certifiés": "أجهزة تتبع 4G معتمدة",
    "Installation sur Site": "تركيب في الموقع",
    "Support 24/7 à Fès": "دعم 24/7 في فاس",
    "Nos Solutions GPS": "حلولنا لنظام GPS",
    "Devis Express Gratuit": "عرض سعر مجاني وسريع",
    "Trackers Installés": "أجهزة تتبع مُركّبة",
    "Flottes Gérées": "أساطيل مُدارة",
    "Disponibilité Serveurs": "توفر الخوادم",
    "Pourquoi Choisir": "لماذا تختار",
    "Nos Solutions de": "حلولنا لـ",
    "Télématique": "تيليماتيك",
    "Découvrir la solution": "اكتشف الحل",
    "Traceurs GPS": "أجهزة تتبع GPS",
    "& Équipements": "والمعدات",
    "Catalogue Complet": "الكتالوج الكامل",
    "En Stock": "متوفر في المخزن",
    "Garanti 1 an": "ضمان لمدة سنة واحدة",
    "Tarif indicatif": "سعر تقريبي",
    "Sur devis": "بناءً على عرض السعر",
    "Commander": "طلب",
    "ESPACE REVENDEURS & GROSSISTES": "مساحة الموزعين وتجار الجملة",
    "Ouvrir un Compte Pro": "فتح حساب احترافي",
    "Ce que disent nos": "ما يقوله",
    "Partenaires": "شركاؤنا",
    "Client Vérifié": "عميل موثق",
    "Ils nous font confiance au Maroc": "يثقون بنا في المغرب",
    "Rencontrez Notre Équipe": "تعرف على فريقنا",
    "Adresse du Siège & Showroom": "عنوان المقر وصالة العرض",
    "Ligne Téléphonique Directe": "رقم الهاتف المباشر",
    "Email Commercial": "البريد الإلكتروني التجاري",
    "Liens Rapides": "روابط سريعة",
    "Nos Solutions": "حلولنا",
    "Contactez-nous": "اتصل بنا",
    "Tous droits réservés.": "جميع الحقوق محفوظة.",
    "Actualités": "الأخبار",
    "Suivi GPS en temps réel": "تتبع GPS في الوقت الحقيقي",
    "Gestion de flotte": "إدارة الأسطول",
    "Contrôle de carburant": "مراقبة الوقود",
    "Surveillance de température": "مراقبة درجة الحرارة",
    "Contactez-nous sur WhatsApp": "تواصل معنا عبر واتساب",
    "Discutez avec nous": "تحدث معنا",
    "Toggle navigation": "تبديل التنقل",
    "Offres & Promotions": "العروض والتخفيضات",
    "Exclusives": "الحصرية",
    "Voir toutes les offres": "عرض جميع العروض",
    "Valable jusqu'au": "صالح حتى",
    "Votre message a été envoyé avec succès.": "تم إرسال رسالتك بنجاح.",
    "Votre demande a été envoyée avec succès.": "تم إرسال طلبك بنجاح.",
    "Votre candidature a été envoyée avec succès.": "تم إرسال طلبك بنجاح.",
    "Vérification anti-spam": "التحقق من مكافحة البريد العشوائي",
    "Réponse incorrecte. Veuillez réessayer.": "إجابة غير صحيحة. يرجى المحاولة مرة أخرى.",
    "Session de vérification expirée.": "انتهت صلاحية جلسة التحقق.",
    "Demande Envoyée": "تم إرسال الطلب",
    "Demande envoyée avec succès !": "تم إرسال الطلب بنجاح!",
    "Retour à l'accueil": "العودة إلى الرئيسية",
    "Téléphone": "الهاتف",
    "Envoyer la demande B2B": "إرسال طلب B2B",
    "Envoyer ma demande": "إرسال طلبي",
    "Profiter de l'offre": "استفد من العرض",
    "Les Avantages du Programme Revendeur": "مزايا برنامج الموزعين",
    "Marges Attractives": "هوامش ربح جذابة",
    "Stock Disponible": "مخزون متوفر",
    "Support & Formation": "دعم وتدريب",
    "Marque Blanche": "علامة بيضاء",
    "Support Marketing": "دعم تسويقي",
    "Gestionnaire Dédié": "مدير مخصص",
    "Niveaux de Partenariat": "مستويات الشراكة",
    "Découverte": "استكشاف",
    "Le plus populaire": "الأكثر شهرة",
    "Pro": "احترافي",
    "Distributeur": "موزع",
    "Demande d'Ouverture de Compte Revendeur": "طلب فتح حساب موزع"
}

def generate_po(lang, d):
    path = os.path.join(base_dir, lang, "LC_MESSAGES")
    os.makedirs(path, exist_ok=True)
    with open(os.path.join(path, "django.po"), "w", encoding="utf-8") as f:
        f.write('msgid ""\n')
        f.write('msgstr ""\n')
        f.write('"Project-Id-Version: m2web\\n"\n')
        f.write('"POT-Creation-Date: 2026-09-30 00:00+0000\\n"\n')
        f.write('"PO-Revision-Date: 2026-09-30 00:00+0000\\n"\n')
        f.write('"MIME-Version: 1.0\\n"\n')
        f.write('"Content-Type: text/plain; charset=UTF-8\\n"\n')
        f.write('"Content-Transfer-Encoding: 8bit\\n"\n')
        f.write('"Language: {}\\n"\n'.format(lang))
        f.write('"Plural-Forms: nplurals=2; plural=(n != 1);\\n"\n\n')
        
        for k, v in d.items():
            f.write(f'msgid "{k}"\n')
            f.write(f'msgstr "{v}"\n\n')

generate_po("en", en_dict)
generate_po("ar", ar_dict)
generate_po("fr", {k: k for k in en_dict.keys()})

print("PO files generated successfully.")
