# Generated by Django 5.1.15 on 2026-09-25 00:30

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_fr', models.CharField(max_length=200, null=True)),
                ('name_ar', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('category', models.CharField(choices=[('obd', 'OBD-II Tracker'), ('hardwired', 'Hardwired Tracker'), ('magnetic', 'Magnetic / Portable'), ('personal', 'Personal / Asset Tracker'), ('sensor', 'Sensor / Accessory')], max_length=20)),
                ('description', models.TextField()),
                ('description_fr', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('specifications', models.TextField(blank=True, help_text='Technical specs, one per line')),
                ('specifications_fr', models.TextField(blank=True, help_text='Technical specs, one per line', null=True)),
                ('specifications_ar', models.TextField(blank=True, help_text='Technical specs, one per line', null=True)),
                ('specifications_en', models.TextField(blank=True, help_text='Technical specs, one per line', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price_range', models.CharField(blank=True, help_text='e.g., 450 - 650 MAD', max_length=100)),
                ('price_range_fr', models.CharField(blank=True, help_text='e.g., 450 - 650 MAD', max_length=100, null=True)),
                ('price_range_ar', models.CharField(blank=True, help_text='e.g., 450 - 650 MAD', max_length=100, null=True)),
                ('price_range_en', models.CharField(blank=True, help_text='e.g., 450 - 650 MAD', max_length=100, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('title_ar', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.TextField(help_text='Short description for cards')),
                ('description_fr', models.TextField(help_text='Short description for cards', null=True)),
                ('description_ar', models.TextField(help_text='Short description for cards', null=True)),
                ('description_en', models.TextField(help_text='Short description for cards', null=True)),
                ('icon_class', models.CharField(default='bi bi-geo-alt', help_text='Bootstrap Icons class', max_length=100)),
                ('detailed_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Contenu détaillé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
    ]
