# Generated by Django 5.1.15 on 2026-09-30 02:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detailed_content_ar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Contenu détaillé'),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Contenu détaillé'),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_content_fr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Contenu détaillé'),
        ),
    ]
