# Generated by Django 5.1.15 on 2026-10-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_detailed_content_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('obd', 'Traceur OBD-II'), ('hardwired', 'Traceur Filaire (Hardwired)'), ('magnetic', 'Traceur Magnétique Autonome'), ('personal', 'Traceur Personnel / Portatif'), ('sensor', 'Capteur & Accessoire')], max_length=20),
        ),
    ]
