# Generated by Django 5.1.15 on 2026-09-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Entreprise'),
        ),
    ]
