# Generated by Django 5.1.15 on 2026-09-25 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('tagline', models.TextField(blank=True)),
                ('tagline_fr', models.TextField(blank=True, null=True)),
                ('tagline_ar', models.TextField(blank=True, null=True)),
                ('tagline_en', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(help_text='International format, e.g. +212662244939', max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Maroc', max_length=100)),
                ('google_maps_url', models.URLField(blank=True)),
                ('google_maps_embed_url', models.URLField(blank=True, help_text='Google Maps iframe embed URL')),
                ('operating_hours_weekday', models.CharField(default='08:30 – 18:30', max_length=100)),
                ('operating_hours_weekday_fr', models.CharField(default='08:30 – 18:30', max_length=100, null=True)),
                ('operating_hours_weekday_ar', models.CharField(default='08:30 – 18:30', max_length=100, null=True)),
                ('operating_hours_weekday_en', models.CharField(default='08:30 – 18:30', max_length=100, null=True)),
                ('operating_hours_saturday', models.CharField(default='08:30 – 13:30', max_length=100)),
                ('operating_hours_saturday_fr', models.CharField(default='08:30 – 13:30', max_length=100, null=True)),
                ('operating_hours_saturday_ar', models.CharField(default='08:30 – 13:30', max_length=100, null=True)),
                ('operating_hours_saturday_en', models.CharField(default='08:30 – 13:30', max_length=100, null=True)),
                ('operating_hours_sunday', models.CharField(default='Fermé', max_length=100)),
                ('operating_hours_sunday_fr', models.CharField(default='Fermé', max_length=100, null=True)),
                ('operating_hours_sunday_ar', models.CharField(default='Fermé', max_length=100, null=True)),
                ('operating_hours_sunday_en', models.CharField(default='Fermé', max_length=100, null=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('analytics_id', models.CharField(blank=True, max_length=50)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_description_fr', models.TextField(blank=True, null=True)),
                ('meta_description_ar', models.TextField(blank=True, null=True)),
                ('meta_description_en', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('role_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('role_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('role_en', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('content_fr', models.TextField(null=True)),
                ('content_ar', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
