# Generated by Django 5.1.15 on 2026-09-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUsPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_fr', models.TextField(null=True, verbose_name='Description')),
                ('description_ar', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('icon_class', models.CharField(default='bi bi-broadcast-pin', help_text='Classe Bootstrap Icons (ex: bi bi-broadcast-pin, bi bi-phone, bi bi-fuel-pump, bi bi-tools)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Pourquoi Nous Choisir (Pilier)',
                'verbose_name_plural': 'Pourquoi Nous Choisir (Piliers)',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'Configuration Générale & Société', 'verbose_name_plural': 'Configuration Générale & Société'},
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_lead',
            field=models.TextField(default='Basée à Fès, M2web Maroc est une entreprise technologique spécialisée dans les solutions de géolocalisation et la gestion de flotte.'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_lead_ar',
            field=models.TextField(default='Basée à Fès, M2web Maroc est une entreprise technologique spécialisée dans les solutions de géolocalisation et la gestion de flotte.', null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_lead_en',
            field=models.TextField(default='Basée à Fès, M2web Maroc est une entreprise technologique spécialisée dans les solutions de géolocalisation et la gestion de flotte.', null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_lead_fr',
            field=models.TextField(default='Basée à Fès, M2web Maroc est une entreprise technologique spécialisée dans les solutions de géolocalisation et la gestion de flotte.', null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_story_title',
            field=models.CharField(default='Notre Histoire & Mission', max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_story_title_ar',
            field=models.CharField(default='Notre Histoire & Mission', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_story_title_en',
            field=models.CharField(default='Notre Histoire & Mission', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_story_title_fr',
            field=models.CharField(default='Notre Histoire & Mission', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_text',
            field=models.TextField(default="Depuis notre création, nous nous sommes engagés à fournir à nos clients des outils fiables, précis et faciles à utiliser pour optimiser leurs opérations logistiques. Notre mission est d'accompagner les entreprises marocaines dans leur transformation numérique en leur offrant une visibilité totale sur leurs actifs mobiles."),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_text_ar',
            field=models.TextField(default="Depuis notre création, nous nous sommes engagés à fournir à nos clients des outils fiables, précis et faciles à utiliser pour optimiser leurs opérations logistiques. Notre mission est d'accompagner les entreprises marocaines dans leur transformation numérique en leur offrant une visibilité totale sur leurs actifs mobiles.", null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_text_en',
            field=models.TextField(default="Depuis notre création, nous nous sommes engagés à fournir à nos clients des outils fiables, précis et faciles à utiliser pour optimiser leurs opérations logistiques. Notre mission est d'accompagner les entreprises marocaines dans leur transformation numérique en leur offrant une visibilité totale sur leurs actifs mobiles.", null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_text_fr',
            field=models.TextField(default="Depuis notre création, nous nous sommes engagés à fournir à nos clients des outils fiables, précis et faciles à utiliser pour optimiser leurs opérations logistiques. Notre mission est d'accompagner les entreprises marocaines dans leur transformation numérique en leur offrant une visibilité totale sur leurs actifs mobiles.", null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='b2b_banner_badge',
            field=models.CharField(default='ESPACE REVENDEURS & GROSSISTES', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='b2b_banner_badge_ar',
            field=models.CharField(default='ESPACE REVENDEURS & GROSSISTES', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='b2b_banner_badge_en',
            field=models.CharField(default='ESPACE REVENDEURS & GROSSISTES', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='b2b_banner_badge_fr',
            field=models.CharField(default='ESPACE REVENDEURS & GROSSISTES', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='b2b_banner_desc',
            field=models.TextField(default="Bénéficiez de tarifs grossiste préférentiels, d'un stock disponible immédiatement à Fès et d'un support technique d'experts pour développer votre activité au Maroc."),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='b2b_banner_desc_ar',
            field=models.TextField(default="Bénéficiez de tarifs grossiste préférentiels, d'un stock disponible immédiatement à Fès et d'un support technique d'experts pour développer votre activité au Maroc.", null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='b2b_banner_desc_en',
            field=models.TextField(default="Bénéficiez de tarifs grossiste préférentiels, d'un stock disponible immédiatement à Fès et d'un support technique d'experts pour développer votre activité au Maroc.", null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='b2b_banner_desc_fr',
            field=models.TextField(default="Bénéficiez de tarifs grossiste préférentiels, d'un stock disponible immédiatement à Fès et d'un support technique d'experts pour développer votre activité au Maroc.", null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='b2b_banner_title',
            field=models.CharField(default='Vous êtes installateur, intégrateur ou revendeur ?', max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='b2b_banner_title_ar',
            field=models.CharField(default='Vous êtes installateur, intégrateur ou revendeur ?', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='b2b_banner_title_en',
            field=models.CharField(default='Vous êtes installateur, intégrateur ou revendeur ?', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='b2b_banner_title_fr',
            field=models.CharField(default='Vous êtes installateur, intégrateur ou revendeur ?', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_badge',
            field=models.CharField(default='N°1 de la Géolocalisation & Télématique au Maroc', max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_badge_ar',
            field=models.CharField(default='N°1 de la Géolocalisation & Télématique au Maroc', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_badge_en',
            field=models.CharField(default='N°1 de la Géolocalisation & Télématique au Maroc', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_badge_fr',
            field=models.CharField(default='N°1 de la Géolocalisation & Télématique au Maroc', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_subtitle',
            field=models.TextField(default='Fournisseur direct de traceurs GPS 4G & solutions télématiques avancées à Fès et partout au Maroc. Réduisez vos coûts de carburant de 20%, protégez vos véhicules contre le vol et suivez vos actifs 24/7 sur smartphone & PC.'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_subtitle_ar',
            field=models.TextField(default='Fournisseur direct de traceurs GPS 4G & solutions télématiques avancées à Fès et partout au Maroc. Réduisez vos coûts de carburant de 20%, protégez vos véhicules contre le vol et suivez vos actifs 24/7 sur smartphone & PC.', null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_subtitle_en',
            field=models.TextField(default='Fournisseur direct de traceurs GPS 4G & solutions télématiques avancées à Fès et partout au Maroc. Réduisez vos coûts de carburant de 20%, protégez vos véhicules contre le vol et suivez vos actifs 24/7 sur smartphone & PC.', null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_subtitle_fr',
            field=models.TextField(default='Fournisseur direct de traceurs GPS 4G & solutions télématiques avancées à Fès et partout au Maroc. Réduisez vos coûts de carburant de 20%, protégez vos véhicules contre le vol et suivez vos actifs 24/7 sur smartphone & PC.', null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_highlight',
            field=models.CharField(default='Total de Votre Flotte', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_highlight_ar',
            field=models.CharField(default='Total de Votre Flotte', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_highlight_en',
            field=models.CharField(default='Total de Votre Flotte', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_highlight_fr',
            field=models.CharField(default='Total de Votre Flotte', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_line1',
            field=models.CharField(default='Prenez le Contrôle', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_line1_ar',
            field=models.CharField(default='Prenez le Contrôle', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_line1_en',
            field=models.CharField(default='Prenez le Contrôle', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_line1_fr',
            field=models.CharField(default='Prenez le Contrôle', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_line2',
            field=models.CharField(default='en Temps Réel', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_line2_ar',
            field=models.CharField(default='en Temps Réel', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_line2_en',
            field=models.CharField(default='en Temps Réel', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title_line2_fr',
            field=models.CharField(default='en Temps Réel', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_trust_badge_1',
            field=models.CharField(default='Traceurs 4G Certifiés', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_trust_badge_1_ar',
            field=models.CharField(default='Traceurs 4G Certifiés', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_trust_badge_1_en',
            field=models.CharField(default='Traceurs 4G Certifiés', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_trust_badge_1_fr',
            field=models.CharField(default='Traceurs 4G Certifiés', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_trust_badge_2',
            field=models.CharField(default='Installation sur Site', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_trust_badge_2_ar',
            field=models.CharField(default='Installation sur Site', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_trust_badge_2_en',
            field=models.CharField(default='Installation sur Site', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_trust_badge_2_fr',
            field=models.CharField(default='Installation sur Site', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_trust_badge_3',
            field=models.CharField(default='Support 24/7 à Fès', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_trust_badge_3_ar',
            field=models.CharField(default='Support 24/7 à Fès', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_trust_badge_3_en',
            field=models.CharField(default='Support 24/7 à Fès', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_trust_badge_3_fr',
            field=models.CharField(default='Support 24/7 à Fès', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone_display',
            field=models.CharField(blank=True, default='06 62 24 49 39', max_length=30),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_experience_count',
            field=models.PositiveIntegerField(default=10, help_text='Années expérience'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_experience_label',
            field=models.CharField(default="Années d'Expertise à Fès", max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_experience_label_ar',
            field=models.CharField(default="Années d'Expertise à Fès", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_experience_label_en',
            field=models.CharField(default="Années d'Expertise à Fès", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_experience_label_fr',
            field=models.CharField(default="Années d'Expertise à Fès", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_fleets_count',
            field=models.PositiveIntegerField(default=350, help_text='Nombre de flottes gérées'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_fleets_label',
            field=models.CharField(default='Flottes Gérées', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_fleets_label_ar',
            field=models.CharField(default='Flottes Gérées', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_fleets_label_en',
            field=models.CharField(default='Flottes Gérées', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_fleets_label_fr',
            field=models.CharField(default='Flottes Gérées', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_trackers_count',
            field=models.PositiveIntegerField(default=5000, help_text='Nombre de traceurs installés'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_trackers_label',
            field=models.CharField(default='Trackers Installés', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_trackers_label_ar',
            field=models.CharField(default='Trackers Installés', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_trackers_label_en',
            field=models.CharField(default='Trackers Installés', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_trackers_label_fr',
            field=models.CharField(default='Trackers Installés', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_uptime_count',
            field=models.CharField(default='99.8%', help_text='Pourcentage disponibilité', max_length=50),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_uptime_label',
            field=models.CharField(default='Disponibilité Serveurs', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_uptime_label_ar',
            field=models.CharField(default='Disponibilité Serveurs', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_uptime_label_en',
            field=models.CharField(default='Disponibilité Serveurs', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='stat_uptime_label_fr',
            field=models.CharField(default='Disponibilité Serveurs', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='topbar_badge',
            field=models.CharField(default='Fournisseur Agréé', help_text='Badge affiché dans la barre supérieure', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='topbar_badge_ar',
            field=models.CharField(default='Fournisseur Agréé', help_text='Badge affiché dans la barre supérieure', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='topbar_badge_en',
            field=models.CharField(default='Fournisseur Agréé', help_text='Badge affiché dans la barre supérieure', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='topbar_badge_fr',
            field=models.CharField(default='Fournisseur Agréé', help_text='Badge affiché dans la barre supérieure', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='topbar_warranty',
            field=models.CharField(default='Garantie & Support Direct', help_text='Texte de garantie dans la topbar', max_length=150),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='topbar_warranty_ar',
            field=models.CharField(default='Garantie & Support Direct', help_text='Texte de garantie dans la topbar', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='topbar_warranty_en',
            field=models.CharField(default='Garantie & Support Direct', help_text='Texte de garantie dans la topbar', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='topbar_warranty_fr',
            field=models.CharField(default='Garantie & Support Direct', help_text='Texte de garantie dans la topbar', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.TextField(default='CN, 2 Rue Ibn Al Kayem, Fès 30000, Maroc'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='city',
            field=models.CharField(default='Fès', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_name',
            field=models.CharField(default='M2web Maroc', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(default='m2web@m2web.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com/m2web.maroc'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='google_maps_embed_url',
            field=models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3306.073998701988!2d-5.0069811!3d34.0419356!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd9f8b484d445777%3A0x10e6aaae728148b5!2s2%20Rue%20Ibn%20Al%20Kayem%2C%20Fes%2030000%2C%20Morocco!5e0!3m2!1sen!2s!4v1700000000000!5m2!1sen!2s', help_text='Google Maps iframe embed URL'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='google_maps_url',
            field=models.URLField(blank=True, default='https://www.google.com/maps/place/M2web+Maroc/data=!4m2!3m1!1s0x0:0xe6a8036782c11407'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com/m2web_maroc'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://linkedin.com/company/m2web-maroc'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(default='+212 6 62 24 49 39', max_length=30),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tagline',
            field=models.TextField(blank=True, default='Solutions Avancées de Géolocalisation & Gestion de Flotte'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tagline_ar',
            field=models.TextField(blank=True, default='Solutions Avancées de Géolocalisation & Gestion de Flotte', null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tagline_en',
            field=models.TextField(blank=True, default='Solutions Avancées de Géolocalisation & Gestion de Flotte', null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tagline_fr',
            field=models.TextField(blank=True, default='Solutions Avancées de Géolocalisation & Gestion de Flotte', null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='whatsapp_number',
            field=models.CharField(default='+212662244939', help_text='Format international sans espaces, ex: +212662244939', max_length=30),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='youtube_url',
            field=models.URLField(blank=True, default='https://youtube.com/@m2webmaroc'),
        ),
    ]
