# Generated by Django 5.1.15 on 2026-09-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_whychooseuspillar_alter_companyinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'offre")),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name="Titre de l'offre")),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name="Titre de l'offre")),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name="Titre de l'offre")),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('badge', models.CharField(default='OFFRE SPÉCIALE', max_length=100, verbose_name='Badge promo (ex: -20%, PROMO FLASH)')),
                ('badge_fr', models.CharField(default='OFFRE SPÉCIALE', max_length=100, null=True, verbose_name='Badge promo (ex: -20%, PROMO FLASH)')),
                ('badge_ar', models.CharField(default='OFFRE SPÉCIALE', max_length=100, null=True, verbose_name='Badge promo (ex: -20%, PROMO FLASH)')),
                ('badge_en', models.CharField(default='OFFRE SPÉCIALE', max_length=100, null=True, verbose_name='Badge promo (ex: -20%, PROMO FLASH)')),
                ('discount_label', models.CharField(blank=True, max_length=50, verbose_name='Remise affichée (ex: -20%, -300 DH)')),
                ('discount_label_fr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Remise affichée (ex: -20%, -300 DH)')),
                ('discount_label_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Remise affichée (ex: -20%, -300 DH)')),
                ('discount_label_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Remise affichée (ex: -20%, -300 DH)')),
                ('summary', models.TextField(verbose_name='Résumé court')),
                ('summary_fr', models.TextField(null=True, verbose_name='Résumé court')),
                ('summary_ar', models.TextField(null=True, verbose_name='Résumé court')),
                ('summary_en', models.TextField(null=True, verbose_name='Résumé court')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description détaillée')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Description détaillée')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description détaillée')),
                ('features', models.TextField(blank=True, help_text='Avantages inclus, un par ligne', verbose_name='Éléments inclus (1 par ligne)')),
                ('features_fr', models.TextField(blank=True, help_text='Avantages inclus, un par ligne', null=True, verbose_name='Éléments inclus (1 par ligne)')),
                ('features_ar', models.TextField(blank=True, help_text='Avantages inclus, un par ligne', null=True, verbose_name='Éléments inclus (1 par ligne)')),
                ('features_en', models.TextField(blank=True, help_text='Avantages inclus, un par ligne', null=True, verbose_name='Éléments inclus (1 par ligne)')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Prix d'origine (DH)")),
                ('promo_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix promotionnel (DH)')),
                ('price_unit', models.CharField(default='/ traceur', max_length=50, verbose_name='Unité de prix (ex: / traceur, / pack)')),
                ('price_unit_fr', models.CharField(default='/ traceur', max_length=50, null=True, verbose_name='Unité de prix (ex: / traceur, / pack)')),
                ('price_unit_ar', models.CharField(default='/ traceur', max_length=50, null=True, verbose_name='Unité de prix (ex: / traceur, / pack)')),
                ('price_unit_en', models.CharField(default='/ traceur', max_length=50, null=True, verbose_name='Unité de prix (ex: / traceur, / pack)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Image illustrative')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Date limite de validité')),
                ('cta_text', models.CharField(default="Profiter de l'offre", max_length=100, verbose_name='Texte du bouton CTA')),
                ('cta_text_fr', models.CharField(default="Profiter de l'offre", max_length=100, null=True, verbose_name='Texte du bouton CTA')),
                ('cta_text_ar', models.CharField(default="Profiter de l'offre", max_length=100, null=True, verbose_name='Texte du bouton CTA')),
                ('cta_text_en', models.CharField(default="Profiter de l'offre", max_length=100, null=True, verbose_name='Texte du bouton CTA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_featured', models.BooleanField(default=False, verbose_name="Mettre en avant sur l'accueil")),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promotion & Offre',
                'verbose_name_plural': 'Promotions & Offres',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone_fix',
            field=models.CharField(default='+212 5 35 94 02 71', max_length=30, verbose_name='Téléphone Fixe'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone_fix_display',
            field=models.CharField(blank=True, default='05 35 94 02 71', max_length=30, verbose_name='Fixe (Affichage)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(default='+212 6 61 76 14 89', max_length=30, verbose_name='Téléphone Mobile'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone_display',
            field=models.CharField(blank=True, default='06 61 76 14 89', max_length=30, verbose_name='Mobile (Affichage)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='whatsapp_number',
            field=models.CharField(default='+212661761489', help_text='Format international sans espaces, ex: +212661761489', max_length=30),
        ),
    ]
