# Generated by Django 5.1.15 on 2026-09-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appfeature_appinquiry_appplan_appscreenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='hero_bg_image',
            field=models.ImageField(blank=True, help_text='Image de fond alternative si pas de vidéo. Taille recommandée: 1920x1080px', null=True, upload_to='hero/', verbose_name='Image de fond Hero'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_bg_overlay_opacity',
            field=models.FloatField(default=0.7, help_text='0.0 = transparent, 1.0 = opaque. Recommandé: 0.6-0.8', verbose_name='Opacité overlay hero'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_bg_video',
            field=models.FileField(blank=True, help_text="Vidéo de fond pour le hero de la page d'accueil. Format MP4, max 10MB recommandé.", null=True, upload_to='hero/', verbose_name='Vidéo de fond Hero (MP4)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='page_header_bg',
            field=models.ImageField(blank=True, help_text='Image de fond par défaut pour les en-têtes de toutes les sous-pages', null=True, upload_to='hero/', verbose_name='Image fond en-tête sous-pages'),
        ),
    ]
