# Generated by Django 5.1.15 on 2026-10-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companyinfo_hero_bg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='about_image',
            field=models.ImageField(blank=True, help_text="Image représentant l'équipe ou les locaux sur la page À Propos. Recommandé: 800x600px", null=True, upload_to='company/', verbose_name='Photo page À Propos'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_slider_image_1',
            field=models.ImageField(blank=True, help_text="Image affichée sur le 1er slide du hero d'accueil.", null=True, upload_to='hero/', verbose_name='Slide Hero 1 (Plateforme & Dashboard)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_slider_image_2',
            field=models.ImageField(blank=True, help_text="Image affichée sur le 2ème slide du hero d'accueil.", null=True, upload_to='hero/', verbose_name='Slide Hero 2 (Suivi de Flotte)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_slider_image_3',
            field=models.ImageField(blank=True, help_text="Image affichée sur le 3ème slide du hero d'accueil.", null=True, upload_to='hero/', verbose_name='Slide Hero 3 (App Mobile & Rapports)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo affiché dans la barre de navigation et le pied de page.', null=True, upload_to='company/', verbose_name='Logo principal du site'),
        ),
        migrations.AddField(
            model_name='whychooseuspillar',
            name='link_url',
            field=models.CharField(blank=True, help_text='URL interne (ex: /services/ ou /mobile-app/ ou /wholesale/) ou externe. Si vide, redirige automatiquement vers la solution correspondante.', max_length=255, verbose_name='Lien de redirection'),
        ),
    ]
