# Generated by Django 5.1.15 on 2026-10-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_companyinfo_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='favicon',
            field=models.ImageField(blank=True, help_text="Icône affichée dans l'onglet du navigateur.", null=True, upload_to='company/', verbose_name='Favicon du site (.ico / .png)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='platform_screenshot',
            field=models.ImageField(blank=True, help_text="Capture d'écran de la plateforme web affichée sur la page Plateforme & Serveur GPS.", null=True, upload_to='platform/', verbose_name="Capture d'écran Plateforme GPS Web"),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='promo_video_url',
            field=models.URLField(blank=True, help_text='Lien vidéo de présentation affiché sur le site web.', verbose_name='URL Vidéo Promotionnelle (YouTube/Vimeo)'),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='ios_coming_soon',
            field=models.BooleanField(default=False, verbose_name='iOS bientôt disponible'),
        ),
    ]
