# Generated by Django 5.1.15 on 2026-10-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_populate_real_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='login_button_text',
            field=models.CharField(blank=True, default='Connexion', help_text='Texte affiché sur le bouton (ex: Connexion, Sign In, Se connecter).', max_length=50, verbose_name='Texte du bouton Connexion'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='login_button_text_ar',
            field=models.CharField(blank=True, default='Connexion', help_text='Texte affiché sur le bouton (ex: Connexion, Sign In, Se connecter).', max_length=50, null=True, verbose_name='Texte du bouton Connexion'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='login_button_text_en',
            field=models.CharField(blank=True, default='Connexion', help_text='Texte affiché sur le bouton (ex: Connexion, Sign In, Se connecter).', max_length=50, null=True, verbose_name='Texte du bouton Connexion'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='login_button_text_fr',
            field=models.CharField(blank=True, default='Connexion', help_text='Texte affiché sur le bouton (ex: Connexion, Sign In, Se connecter).', max_length=50, null=True, verbose_name='Texte du bouton Connexion'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='login_button_title',
            field=models.CharField(blank=True, default='Connexion Plateforme Trackmaroc', help_text='Texte affiché au survol du bouton (tooltip/alt text).', max_length=150, verbose_name='Infobulle du bouton Connexion (alt/title)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='login_button_title_ar',
            field=models.CharField(blank=True, default='Connexion Plateforme Trackmaroc', help_text='Texte affiché au survol du bouton (tooltip/alt text).', max_length=150, null=True, verbose_name='Infobulle du bouton Connexion (alt/title)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='login_button_title_en',
            field=models.CharField(blank=True, default='Connexion Plateforme Trackmaroc', help_text='Texte affiché au survol du bouton (tooltip/alt text).', max_length=150, null=True, verbose_name='Infobulle du bouton Connexion (alt/title)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='login_button_title_fr',
            field=models.CharField(blank=True, default='Connexion Plateforme Trackmaroc', help_text='Texte affiché au survol du bouton (tooltip/alt text).', max_length=150, null=True, verbose_name='Infobulle du bouton Connexion (alt/title)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='login_button_url',
            field=models.URLField(blank=True, default='https://trackmaroc.com', help_text='URL de redirection du bouton "Connexion" dans la barre de navigation (ex: https://trackmaroc.com).', verbose_name='Lien du bouton Connexion'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='quote_button_text',
            field=models.CharField(blank=True, default='Demander un Devis', help_text='Texte affiché sur le bouton devis (ex: Demander un Devis, Request a Quote).', max_length=50, verbose_name='Texte du bouton Devis'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='quote_button_text_ar',
            field=models.CharField(blank=True, default='Demander un Devis', help_text='Texte affiché sur le bouton devis (ex: Demander un Devis, Request a Quote).', max_length=50, null=True, verbose_name='Texte du bouton Devis'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='quote_button_text_en',
            field=models.CharField(blank=True, default='Demander un Devis', help_text='Texte affiché sur le bouton devis (ex: Demander un Devis, Request a Quote).', max_length=50, null=True, verbose_name='Texte du bouton Devis'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='quote_button_text_fr',
            field=models.CharField(blank=True, default='Demander un Devis', help_text='Texte affiché sur le bouton devis (ex: Demander un Devis, Request a Quote).', max_length=50, null=True, verbose_name='Texte du bouton Devis'),
        ),
    ]
