# Generated by Django 5.1.15 on 2026-09-25 00:30

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('name_fr', models.CharField(max_length=200, null=True, verbose_name='Nom')),
                ('name_ar', models.CharField(max_length=200, null=True, verbose_name='Nom')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Nom')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=300, null=True, verbose_name='Titre')),
                ('title_ar', models.CharField(max_length=300, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Titre')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary for listing pages', max_length=500, verbose_name='Extrait')),
                ('excerpt_fr', models.TextField(help_text='Short summary for listing pages', max_length=500, null=True, verbose_name='Extrait')),
                ('excerpt_ar', models.TextField(help_text='Short summary for listing pages', max_length=500, null=True, verbose_name='Extrait')),
                ('excerpt_en', models.TextField(help_text='Short summary for listing pages', max_length=500, null=True, verbose_name='Extrait')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenu')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Image mise en avant')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Méta description')),
                ('meta_description_fr', models.CharField(blank=True, max_length=160, null=True, verbose_name='Méta description')),
                ('meta_description_ar', models.CharField(blank=True, max_length=160, null=True, verbose_name='Méta description')),
                ('meta_description_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Méta description')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
