# Generated by Django 5.1.15 on 2026-09-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('contact_person', models.CharField(max_length=200, verbose_name='Personne de contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('monthly_volume', models.CharField(choices=[('10-50', '10 – 50 unités/mois'), ('50-200', '50 – 200 unités/mois'), ('200+', '200+ unités/mois')], max_length=10, verbose_name='Volume mensuel')),
                ('hardware_types_needed', models.TextField(help_text='Types of GPS trackers needed', verbose_name="Types d'équipements souhaités")),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Demande B2B',
                'verbose_name_plural': 'Demandes B2B',
                'ordering': ['-created_at'],
            },
        ),
    ]
