# Generated by Django 5.1.15 on 2026-09-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise / Organisation")),
                ('contact_name', models.CharField(max_length=200, verbose_name='Nom du responsable')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone / WhatsApp')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('acquisition_mode', models.CharField(choices=[('rent_saas', 'Location / Abonnement SaaS (Par véhicule / mois ou an)'), ('buy_server', 'Achat de Serveur / Licence Définitive On-Premise'), ('whitelabel', 'Plateforme Serveur en Marque Blanche Complète (Logo + Domaine + App)'), ('custom', 'Développement / Intégration sur-mesure (API / ERP / Télématique)')], default='rent_saas', max_length=20, verbose_name='Formule souhaitée')),
                ('fleet_size', models.CharField(choices=[('1-10', '1 à 10 véhicules'), ('11-50', '11 à 50 véhicules'), ('51-200', '51 à 200 véhicules'), ('200+', 'Plus de 200 véhicules')], default='11-50', max_length=20, verbose_name='Taille de la flotte')),
                ('needs_reports', models.BooleanField(default=True, verbose_name='Besoin de rapports avancés & statistiques')),
                ('needs_fuel_sensor', models.BooleanField(default=False, verbose_name='Besoin de contrôle carburant / sondes')),
                ('message', models.TextField(blank=True, verbose_name='Détails du projet / Questions')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
            ],
            options={
                'verbose_name': 'Demande Plateforme & Serveur',
                'verbose_name_plural': 'Demandes Plateforme & Serveur',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise / Atelier")),
                ('contact_person', models.CharField(max_length=200, verbose_name='Nom & Prénom du responsable')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone / WhatsApp')),
                ('city', models.CharField(max_length=100, verbose_name="Ville d'activité")),
                ('activity_type', models.CharField(choices=[('auto_electrician', 'Électricien auto / Installateur'), ('it_telecom', 'Revendeur informatique & télécom'), ('security', 'Société de sécurité / Gardiennage'), ('car_rental', 'Loueur de véhicules / Agence de transport'), ('distributor', 'Grossiste / Distributeur commercial'), ('other', 'Autre professionnel')], default='auto_electrician', max_length=30, verbose_name="Secteur d'activité")),
                ('expected_volume', models.CharField(choices=[('5-15', '5 – 15 traceurs / mois (Pack Découverte)'), ('15-50', '15 – 50 traceurs / mois (Pack Pro Installateur)'), ('50+', '50+ traceurs / mois (Distributeur Régional)'), ('server', 'Projet Serveur Dédié / Marque Blanche')], default='5-15', max_length=20, verbose_name='Volume mensuel estimé')),
                ('has_installed_before', models.BooleanField(default=False, verbose_name='Avez-vous déjà installé des traceurs GPS ?')),
                ('interested_in_whitelabel', models.BooleanField(default=False, verbose_name='Intéressé par une plateforme en Marque Blanche')),
                ('message', models.TextField(blank=True, verbose_name='Message / Besoins particuliers')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
            ],
            options={
                'verbose_name': 'Candidature Revendeur',
                'verbose_name_plural': 'Candidatures Revendeurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
