# Generated by Django 5.1.15 on 2026-10-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0002_platforminquiry_resellerinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=100, null=True, verbose_name='Titre')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_fr', models.TextField(null=True, verbose_name='Description')),
                ('description_ar', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('badge_text', models.CharField(blank=True, max_length=50, verbose_name='Texte du badge')),
                ('badge_text_fr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texte du badge')),
                ('badge_text_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texte du badge')),
                ('badge_text_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texte du badge')),
                ('icon_class', models.CharField(blank=True, max_length=50, verbose_name="Classe de l'icône (ex: bi-star)")),
                ('badge_style', models.CharField(choices=[('light', 'Light'), ('amber', 'Amber'), ('plum', 'Plum')], default='light', max_length=20, verbose_name='Style du badge')),
                ('volume_min', models.IntegerField(default=0, verbose_name='Volume minimum')),
                ('volume_max', models.IntegerField(default=0, help_text='0 pour "et plus"', verbose_name='Volume maximum')),
                ('volume_label', models.CharField(max_length=50, verbose_name='Label du volume')),
                ('volume_label_fr', models.CharField(max_length=50, null=True, verbose_name='Label du volume')),
                ('volume_label_ar', models.CharField(max_length=50, null=True, verbose_name='Label du volume')),
                ('volume_label_en', models.CharField(max_length=50, null=True, verbose_name='Label du volume')),
                ('discount_text', models.CharField(max_length=100, verbose_name='Texte de la remise')),
                ('discount_text_fr', models.CharField(max_length=100, null=True, verbose_name='Texte de la remise')),
                ('discount_text_ar', models.CharField(max_length=100, null=True, verbose_name='Texte de la remise')),
                ('discount_text_en', models.CharField(max_length=100, null=True, verbose_name='Texte de la remise')),
                ('features', models.TextField(help_text='Une fonctionnalité par ligne', verbose_name='Fonctionnalités')),
                ('features_fr', models.TextField(help_text='Une fonctionnalité par ligne', null=True, verbose_name='Fonctionnalités')),
                ('features_ar', models.TextField(help_text='Une fonctionnalité par ligne', null=True, verbose_name='Fonctionnalités')),
                ('features_en', models.TextField(help_text='Une fonctionnalité par ligne', null=True, verbose_name='Fonctionnalités')),
                ('cta_text', models.CharField(max_length=100, verbose_name='Texte du bouton')),
                ('cta_text_fr', models.CharField(max_length=100, null=True, verbose_name='Texte du bouton')),
                ('cta_text_ar', models.CharField(max_length=100, null=True, verbose_name='Texte du bouton')),
                ('cta_text_en', models.CharField(max_length=100, null=True, verbose_name='Texte du bouton')),
                ('cta_url', models.CharField(default='#resellerFormSection', max_length=200, verbose_name='Lien du bouton')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Niveau Revendeur',
                'verbose_name_plural': 'Niveaux Revendeur',
                'ordering': ['order'],
            },
        ),
    ]
