# Generated by Django 5.1.15 on 2026-10-05 20:37

from django.db import migrations

def populate_tiers(apps, schema_editor):
    ResellerTier = apps.get_model('wholesale', 'ResellerTier')
    
    ResellerTier.objects.create(
        title_fr="Pack Découverte",
        title_ar="باقة الاكتشاف",
        title_en="Discovery Pack",
        description_fr="Pour les nouveaux installateurs et électriciens auto qui débutent.",
        description_ar="لفنيي التركيب وكهربائيي السيارات المبتدئين.",
        description_en="For new installers and auto electricians getting started.",
        badge_text_fr="DÉMARRAGE",
        badge_text_ar="الانطلاق",
        badge_text_en="STARTER",
        badge_style="light",
        volume_min=1,
        volume_max=10,
        volume_label_fr="unités / mois",
        volume_label_ar="وحدة / شهر",
        volume_label_en="units / month",
        discount_text_fr="Remise grossiste ~15%",
        discount_text_ar="خصم جملة ~15%",
        discount_text_en="Wholesale discount ~15%",
        features_fr="Idéal pour tester le matériel\nSans engagement de durée\nSchémas de câblage et formation inclus\nSupport technique WhatsApp direct\nAccès à la plateforme de tracking",
        features_ar="مثالي لاختبار الأجهزة\nبدون أي التزام زمني\nمخططات التوصيل والتدريب مشمولان\nدعم فني مباشر عبر واتساب\nولوج لمنصة التتبع",
        features_en="Ideal for testing equipment\nNo time commitment\nWiring diagrams and training included\nDirect WhatsApp technical support\nAccess to tracking platform",
        cta_text_fr="Devenir Revendeur Découverte",
        cta_text_ar="كن موزعاً في باقة الاكتشاف",
        cta_text_en="Become a Discovery Reseller",
        is_featured=False,
        order=1
    )

    ResellerTier.objects.create(
        title_fr="Pro Installateur",
        title_ar="المحترف فني التركيب",
        title_en="Pro Installer",
        description_fr="Pour les professionnels actifs avec des installations régulières.",
        description_ar="للمهنيين النشطين وأصحاب التركيبات المنتظمة.",
        description_en="For active professionals with regular installations.",
        badge_text_fr="LE PLUS POPULAIRE",
        badge_text_ar="الأكثر طلباً",
        badge_text_en="MOST POPULAR",
        badge_style="amber",
        volume_min=10,
        volume_max=50,
        volume_label_fr="unités / mois",
        volume_label_ar="وحدة / شهر",
        volume_label_en="units / month",
        discount_text_fr="Remise grossiste ~25%",
        discount_text_ar="خصم جملة ~25%",
        discount_text_en="Wholesale discount ~25%",
        features_fr="Tarifs grossistes très avantageux\nStock prioritaire garanti disponible à Fès\nOption Marque Blanche plateforme\nSupports marketing et fiches fournis\nGestionnaire de compte dédié",
        features_ar="أسعار جملة تفضيلية ومغرية\nمخزون ذو أولوية مضمون متوفر بفاس\nخيار منصة بعلامتك البيضاء\nتوفير المنشورات والكتالوجات التسويقية\nمدير حساب مخصص",
        features_en="Very competitive wholesale prices\nGuaranteed priority stock available in Fez\nWhite Label platform option\nMarketing materials and datasheets provided\nDedicated account manager",
        cta_text_fr="Rejoindre le Réseau Pro",
        cta_text_ar="الانضمام لشبكة المحترفين",
        cta_text_en="Join the Pro Network",
        is_featured=True,
        order=2
    )

    ResellerTier.objects.create(
        title_fr="Distributeur Régional",
        title_ar="موزع إقليمي",
        title_en="Regional Distributor",
        description_fr="Pour les grossistes, entreprises de sécurité et distributeurs régionaux.",
        description_ar="لتجار الجملة، شركات الحراسة والموزعين الإقليميين.",
        description_en="For wholesalers, security companies and regional distributors.",
        badge_text_fr="EXCLUSIF",
        badge_text_ar="حصري",
        badge_text_en="EXCLUSIVE",
        badge_style="plum",
        volume_min=50,
        volume_max=0,
        volume_label_fr="unités / mois",
        volume_label_ar="وحدة / شهر",
        volume_label_en="units / month",
        discount_text_fr="Remise maximale jusqu'à 35%",
        discount_text_ar="أقصى نسبة خصم تصل الى 35%",
        discount_text_en="Maximum discount up to 35%",
        features_fr="Meilleure grille tarifaire au Maroc\nPlateforme & App Marque Blanche offertes\nExclusivité régionale selon secteur\nServeur dédié & intégrations API ERP\nConditions de paiement flexibles",
        features_ar="أفضل جدول أسعار في المغرب\nمنصة وتطبيق مجاناً بعلامتك التجارية\nحصرية إقليمية حسب المنطقة\nخادم مخصص وتكامل API مع ERP\nتسهيلات وشروط دفع مرنة",
        features_en="Best pricing in Morocco\nFree White Label platform & app\nRegional exclusivity by area\nDedicated server & API ERP integrations\nFlexible payment terms",
        cta_text_fr="Postuler comme Distributeur",
        cta_text_ar="التقديم كموزع إقليمي",
        cta_text_en="Apply as Distributor",
        is_featured=False,
        order=3
    )

def remove_tiers(apps, schema_editor):
    ResellerTier = apps.get_model('wholesale', 'ResellerTier')
    ResellerTier.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0003_resellertier'),
    ]

    operations = [
        migrations.RunPython(populate_tiers, reverse_code=remove_tiers),
    ]
